apiVersion: v1
kind: Pod
metadata:
  name: anthos-gitops-nginx-pod
  namespace: anthos-gitops-ns
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
